export enum BasicInfoEnum {
    FIRSTNAME = "FIRSTNAME",
    MIDDLENAME = "MIDDLENAME",
    LASTNAME = "LASTNAME",
    NICKNAME = "NICKNAME",
    GENDER = "GENDER",
    NATIONALITY = "NATIONALITY",
    NATION = "NATION",
    RELIGION = "RELIGION",
    RELATIONSHIPSTATUS = "RELATIONSHIPSTATUS",
    HOMETOWN = "HOMETOWN",
    DAYOFBIRTH = "DAYOFBIRTH",
    MONTHOFBIRTH = "MONTHOFBIRTH",
    YEAROFBIRTH = "YEAROFBIRTH"
}

export enum AdvanceInfoEnum {

}

export enum AddressInfoEnum {
    PERMANENTADDRESS = "PERMANENTADDRESSNOTE",
    PERMANENTADDRESSNOTE = "PERMANENTADDRESSNOTE",
    TEMPORARYADDRESS = "TEMPORARYADDRESS",
    HOMEADDRESS = "HOMEADDRESS",
    TEMPORARYADDRESSNOTE = "TEMPORARYADDRESSNOTE"
}