export enum BasicInfoEnum {
    FIRSTNAME = "FIRSTNAME",
    MIDDLENAME = "MIDDLENAME",
    LASTNAME = "LASTNAME",
    NICKNAME = "NICKNAME",
    GENDER = "GENDER",
    NATIONALITY = "NATIONALITY",
    NATION = "NATION",
    RELIGION = "RELIGION",
    RELATIONSHIPSTATUS = "RELATIONSHIPSTATUS",
    HOMETOWN = "HOMETOWN",
    DAYOFBIRTH = "DAYOFBIRTH",
    MONTHOFBIRTH = "MONTHOFBIRTH",
    YEAROFBIRTH = "YEAROFBIRTH"
}

export enum AdvanceInfoEnum {
    IDENTITYCARDNUMBER = "IDENTITYCARDNUMBER",
    IDENTITYCARDDATE = "IDENTITYCARDDATE",
    EXPIREIDENTITYCARDDATE = "IDENTITYCARDDATE",
    IDENTITYCARDiSSUEBY = "IDENTITYCARDiSSUEBY",

    IDENTITYNUMBER = "IDENTITYNUMBER",
    IDENTITYDATE = "IDENTITYDATE",
    EXPIREIDENTITYDATE = "EXPIREIDENTITYDATE",

    TAXNUMBER = "TAXNUMBER",
    REGISTRATIONDATE = "REGISTRATIONDATE",
    REGISTRATIONPLACE = "REGISTRATIONPLACE",

    PASSPORTNUMBER = "PASSPORTNUMBER",
    PASSPORTDATE = "PASSPORTDATE",
    EXPIREDPASSPORTDATE = "EXPIREPASSPORTDATE",
    VISAISSUEDBY = "VISAISSUEDBY",
    PASSPORTTYPE = "PASSPORTTYPE",

    VISANUMBER = "VISANUMBER",
    VISADATE = "VISADATE",
    EXPIREDVISADATE = "EXPIREDVISADATE",
    NATION =  "NATION"
}

export enum AddressInfoEnum {
    PERMANENTADDRESS = "PERMANENTADDRESS",
    PERMANENTADDRESSNOTE = "PERMANENTADDRESSNOTE",
    TEMPORARYADDRESS = "TEMPORARYADDRESS",
    HOMEADDRESS = "HOMEADDRESS",
    TEMPORARYADDRESSNOTE = "TEMPORARYADDRESSNOTE"
}